version: "3.9"

services:
  realtime-bus:
    image: "redis:alpine"
    ports:
      - "16666:6379"
    volumes:
      - realtime-bus-data:/data
    networks:
      - wuret
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672

volumes:
  realtime-bus-data: null

networks:
  wuret:
    external: true